web_registration/serials/urls.py
# -*- coding: utf-8 -*-
"""
:synopsis:   Django URL settings for serials app.
             When including this in another urls.py, please, put it in serials 
             namespace. Ex.: 
               url( r'^users/', include('serials.urls', namespace='serials') )

:created:    2014-09-17

:author:     Óscar Gallardo (ogallard@gmail.com) at LP-CSIC/UAB (lp.csic@uab.cat)
:copyright:  2014 LP-CSIC/UAB (http://proteomica.uab.cat). Some rights reserved.
:license:    GPLv3 (http://www.gnu.org/licenses/gpl-3.0.html)

:contact:    lp.csic@uab.cat

:version:    0.1 dev
:updated:    2014-09-19
"""

#===============================================================================
# Imports
#===============================================================================
# Django imports:
from django.conf.urls import patterns, url

# Application imports:
from serials.views import UserMain


#===============================================================================
# URL patterns variable
#===============================================================================
urlpatterns = patterns('',
    url(r'^(?P<user_name>.*)$', UserMain.as_view(), 
        name='user_main'),
)

web_registration/web_registration/urls.py
# -*- coding: utf-8 -*-
"""
:synopsis:   Django URL settings for web_registration project.

:created:    2014-09-11

:author:     Óscar Gallardo (ogallard@gmail.com) at LP-CSIC/UAB (lp.csic@uab.cat)
:copyright:  2014 LP-CSIC/UAB (http://proteomica.uab.cat). Some rights reserved.
:license:    GPLv3 (http://www.gnu.org/licenses/gpl-3.0.html)

:contact:    lp.csic@uab.cat

:version:    0.1 dev
:updated:    2014-09-23
"""

#===============================================================================
# Imports
#===============================================================================
# Django imports:
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

# Application imports:
from basic_classes import BasicHtmlPage
from views import Register


#===============================================================================
# URL patterns variable
#===============================================================================
admin.autodiscover()

#Common extra context dictionaries:
extra_context_reset_password = {
                                'base_template': 'base.html', 
                                'css_sheet': 'default.css', 
                                'APPNAME': settings.APPNAME, 
                                'section_title': 'Reset password', 
                                'class_login': r'current'
                                }
extra_context_register = {
                          'base_template': 'base.html', 
                          'css_sheet': 'default.css', 
                          'APPNAME': settings.APPNAME, 
                          'section_title': 'Register', 
                          'class_register': r'current'
                          }

urlpatterns = patterns('',
    url(r'^$', BasicHtmlPage.as_view(template_name='home_section.html'), 
        {'extra_context': {'section_title': 'Home Page', 
                           'class_home': r'current'}}, 
        name='home'
        ), 
    url(r'^about$', BasicHtmlPage.as_view(template_name='home_section.html'), 
       {'extra_context': {'section_title': 'About', 
                          'class_about': r'current'}}, 
        name='about'
        ), 
    url(r'^help$', BasicHtmlPage.as_view(template_name='home_section.html'), 
        {'extra_context': {'section_title': 'Help', 
                           'class_help': r'current'}}, 
        name='help'
        ), 
    url(r'^todo$', BasicHtmlPage.as_view(template_name='home_section.html'), 
        {'extra_context': {'section_title': 'To-Do', 
                           'class_todo': r'current'}}, 
        name='todo'
        ), 
    url(r'^login$', 'django.contrib.auth.views.login', 
        {'template_name': 'login.html', 
         'extra_context': {'base_template': 'base.html', 
                           'css_sheet': 'default.css', 
                           'APPNAME': settings.APPNAME, 
                           'section_title': 'Login', 
                           'class_login': r'current'}}, 
        name='login'
        ), 
    url(r'^logout$', 'django.contrib.auth.views.logout_then_login', 
        name='logout'
        ), 
    url(r'^password_reset$', 'django.contrib.auth.views.password_reset', 
        {'template_name': 'password_reset.html', 
         'email_template_name': 'password_reset_email.html', 
         'subject_template_name': 'password_reset_subject.txt', 
         'extra_context': extra_context_reset_password}, 
        name='password_reset'
        ), 
    url(r'^password_reset_done$', 'django.contrib.auth.views.password_reset_done', 
        {'template_name': 'password_reset_done.html', 
         'extra_context': extra_context_reset_password}, 
        name='password_reset_done'
        ), 
    url(r'^password_reset_confirm/(?P<uidb64>.*)/(?P<token>.*)$', 'django.contrib.auth.views.password_reset_confirm', 
        {'template_name': 'password_reset_confirm.html', 
         'extra_context': extra_context_reset_password}, 
        name='password_reset_confirm'
        ), 
    url(r'^password_reset_complete$', 'django.contrib.auth.views.password_reset_complete', 
        {'template_name': 'password_reset_complete.html', 
         'extra_context': extra_context_reset_password}, 
        name='password_reset_complete'
        ), 
    url(r'^registering$', Register.as_view(), 
        {'extra_context': extra_context_register}, 
        name='register'
        ), 
    url(r'^register_done$', 'django.contrib.auth.views.password_reset_done', 
        {'template_name': 'register_done.html', 
         'extra_context': extra_context_register}, 
        name='register_done'
        ), 
    url(r'^register_confirm/(?P<uidb64>.*)/(?P<token>.*)$', 'django.contrib.auth.views.password_reset_confirm', 
        {'template_name': 'register_confirm.html', 
         'extra_context': extra_context_register}, 
        name='register_confirm'
        ), 
    url(r'^register_complete$', 'django.contrib.auth.views.password_reset_complete', 
        {'template_name': 'register_complete.html', 
         'extra_context': extra_context_register}, 
        name='register_complete'
        ), 
    url( r'^admin/', include(admin.site.urls) ), 
    url( r'^users/', include('serials.urls', namespace='serials'), 
         { 'extra_context': {'class_users':r'current'} } 
         ), 
)

web_registration/templates/about_section.html
{% extends base_template %}

{% block section %}
    <div id="content">
        <h3>About <span style="color: #FF9030;">{{APPNAME}}</span></h3>
        <p>{{APPNAME}} is a continuous evolving PhosphoProteome DataBase for {{CELLTYPE}}. 
        And it's also a Web-Application that allows everyone to 
        freely access all this information from the Internet.</p>

        <h4>PhosphoProteome</h4>
        <p>Protein phosphorylation-dephosphorylation events play a primordial role 
        in almost all aspects of cell function including signal transduction, cell 
        cycle and apoptosis. Phosphorylation is probably the most frequent reversible 
        posttranslational modification of proteins (about 30% of the cell proteins 
        are phosphorylated in a given condition). However, the number of known <i>in 
        vivo</i> substrates of kinases is still low.</p>
        
        <h4>Where <span style="color: #FF9030;">{{APPNAME}}</span> comes from?</h4>
        <p>LymPHOS data has been obtained at the <a href="http://proteomica.uab.cat" title="CSIC/UAB Proteomics Laboratory WebPage" target="_blank">CSIC/UAB
        Proteomics Laboratory</a> of the Superior Council of Scientific Research mainly
        under a Spanish Research Project funded by Research and Education Ministry
        (BIO2004-01788) during the period 2004-2011. In this project we intend to study,
        using a proteomic approach, the phosphoproteome of resting and physiologically
        or pharmacologically activated T and B lymphocytes. The main objective was the
        design of a coherent and comprehensive database of phosphoproteins and
        phosphorylation sites in these cells. The characterization of phosphorylation
        motifs will help in the search for new, physiologically relevant kinases as well
        as in the understanding of the mechanisms involved in the regulation of protein
        function. This information is the first step towards the design of new therapies
        based in drugs controlling either kinase/phosphatase activities or the activity
        of other proteins in key points of the affected pathways.</p>
        
        <a name="credits"></a>
        <h3>Credits</h3>
        <p>This work has been carried out at <a href="http://proteomica.uab.cat" 
        title="CSIC/UAB Proteomics Laboratory WebPage" target="_blank">CSIC/UAB
        Proteomics Laboratory</a>, part of the <a href="http://www.csic.es" 
        title="Spanish National Research Council (CSIC) WebPage" target="_blank">
        Spanish National Research Council (<i>Consejo Superior de Investigaciones 
        Cient&iacute;ficas</i> - CSIC)</a>, from Catalonia (Spain), and part of
        <a href="http://www.proteored.org/" title="ProteoRed WebPage" 
        target="_blank">ProteoRed (Proteomics National NetWork Platform)</a>.</p>
        <p>The people who has participated directly in the current work are:</p>
        <ul>
            <li>Mass Spectrometry, study design and implementation: <em title="montserrat.carrascal.csic &lt;at&gt; uab.cat">Montserrat Carrascal</em>, <em title="mgmbam &lt;at&gt; iibb.csic.es">Marina Gay</em> and <em title="nguyentiendung_bk &lt;at&gt; yahoo.com">Nguyen TienDung</em></li>
            <li>Sample preparation: <em title="montserrat.carrascal.csic &lt;at&gt; uab.cat">Montserrat Carrascal</em>, <em title="mgmbam &lt;at&gt; iibb.csic.es">Marina Gay</em>, <em title="nguyentiendung_bk &lt;at&gt; yahoo.com">Nguyen TienDung</em> and <em title="vcasaslopez &lt;at&gt; gmail.com">Vanessa Casas</em></li>
            <li>Data analysis, bioinformatics and informatics: <em title="joaquin.abian.csic &lt;at&gt; uab.cat">Joaquin Abian</em> and <em title="ogallardo &lt;at&gt; proteored.org">&Oacute;scar Gallardo</em></li>    
            <li>Direction: <em title="joaquin.abian.csic &lt;at&gt; uab.cat">Joaquin Abian</em></li>
        </ul>
        <a name="contact"></a>
        <h3>Contact data</h3>
        <a href="http://proteomica.uab.cat" title="CSIC/UAB Proteomics Laboratory WebPage" target="_blank">
        <img alt="LP CSIC/UAB Logo" src="/files/images/logo_lpcsicuab.png" class="right"></a>
        <p><a href="http://proteomica.uab.cat" title="CSIC/UAB Proteomics Laboratory WebPage" target="_blank"><b>Laboratorio de Proteomica CSIC/UAB</b></a><br/>
        Facultad de Medicina, Edificio M, Campus UAB<br/>
        08193, Cerdanyola (Barcelona), Spain<br/>
        <img src="/files/images/contact.png" title="lp.csic &lt;at&gt; uab.cat"/><br/>
        Phone number: <b>+34 93 581 48 55</b></p>
    </div>
{% endblock %}

web_registration/templates/base.html
{# Main Base Django template for the web_registratio Project #}

{% load staticfiles %}

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=8,chrome=1" />
        <meta name="Author" content="Óscar Gallardo at LP-CSIC/UAB" />
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
        <link rel="icon" href="{% static 'images/animated_favicon.gif' %}" type="image/gif" />
        <link href="{% static 'css/'|add:css_sheet %}" rel="stylesheet" type="text/css" />
        <title>{{APPNAME}}{% if section_title %} - {{section_title}}{% endif %}</title>
    </head>

    <body>
        {# {% spaceless %} #}
        <a name="top"></a>
        <div id="wrap">
            <div id="header">
                <h1>
                    <a rel="start" href="/"><img src="{% static 'images/logo.png' %}" alt="logo" title="LP-CSIC/UAB web registratio"/></a>
                </h1>
                <h2>
                    (cc) 2014 <a rel="copyright" href="http://proteomica.uab.cat" title="CSIC/UAB Proteomics Laboratory" target="_blank">Laboratori de Prote&ograve;mica CSIC/UAB</a>
                </h2>
            </div>
            
            <div id="menucontainer">
                {% include 'nav_bar.html' %}
            </div>
    
            <div id="container">
                {# And now the main content of the current section #}
                {% block section %}{% endblock %}
            </div>
    
            <div id="footer">
                {% include 'footer.html' %}
            </div>
        </div>
        {# {% endspaceless %} #}
    </body>

</html>

web_registration/templates/home_section.html
{% extends base_template %}

{% load staticfiles %}

{% block section %}
    <div id="content">
        <h3>Welcome to <span style="color: #FF9030;">{{APPNAME}}</span></h3>
        <p>{{APPNAME}} is a web-oriented DataBase containing peptidic and protein sequences 
        and spectrometric information on the PhosphoProteome of .</p>
        <p>More detailed information on this site and the people at the <a href="http://proteomica.uab.cat" title="CSIC/UAB Proteomics Laboratory WebPage" target="_blank">CSIC/UAB
        Proteomics Laboratory</a> behind it can be obtained at the <a rel="section" href="{% url 'about' %}" title="About {{APPNAME}}">About</a> section.</p>       
    </div>
{% endblock %}

web_registration/templates/login.html
{% extends base_template %}

{% load staticfiles %}

{% block section %}

{% if user.is_authenticated %}

  <p>Hello <a href="{% url 'serials:user_main' user_name=user.username %}">{{user.username}}</a>, you are logged-in.</p>

{% else %}

  {% if form.errors %}
    <p class="error">Your username and password don't match. Please try again:</p>
  {% else %}
    <p>Please, enter your username and password to log-in:</p>
  {% endif %}
  
  <form method="post" action="">
    {% csrf_token %}
    <table>
    <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
    </tr>
    <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
    </tr>
    <tr>
      <td><button type="submit" value="login" name="login" title="Log-in with given username and password">
        <img alt="" src="{% static 'images/key.png' %}"/>&nbsp;Log-in!
      </button></td>
      <td><button type="reset" value="reset" name="reset" title="Resets username and password fileds">
        <img alt="" src="{% static 'images/eraser.png' %}"/>&nbsp;Clear
      </button></td>
    </tr>
    </table>
    <input type="hidden" name="next" value="{{ next }}" />
  </form>
  
  <p>If you forgot your password, <a href="{% url 'password_reset' %}">click here</a> to get an e-mail with a password-reset link.</p>
  <p>You can also <a href="{% url 'register' %}">register as a new user...</a></p>
  
{% endif %}

{% endblock %}

web_registration/templates/nav_bar.html
<div id="menunav">
  <ul>
    {% if user.is_authenticated %}
      <li><a rel="section" class="{{class_users}}" href="{% url 'serials:user_main' user_name=user.username %}" title="{{APPNAME}} Home Page for {{user.username}}"><span>User</span></a></li>
    {% else %}
      <li><a rel="section" class="{{class_home}}" href="{% url 'home' %}" title="{{APPNAME}} Home Page"><span>Home</span></a></li>
    {% endif %}
    <li><a rel="section" class="{{class_about}}" href="{% url 'about' %}" title="About {{APPNAME}}"><span>About</span></a></li>
    {% if user.is_authenticated %}
      <li><a rel="section" class="{{class_logout}}" href="{% url 'logout' %}" title="Logout {{user.username}} from {{APPNAME}}"><span>Logout</span></a></li>
    {% else %}
      <li><a rel="section" class="{{class_login}}" href="{% url 'login' %}" title="Login {{APPNAME}}"><span>Login</span></a></li>
      <li><a rel="section" class="{{class_register}}" href="{% url 'register' %}" title="Register in {{APPNAME}}"><span>Register</span></a></li>
    {% endif %}
    <li><a rel="section" class="{{class_help}}" href="{% url 'help' %}" title="{{APPNAME}} Help"><span>Help</span></a></li>
    <li><a rel="section" class="{{class_todo}}" href="{% url 'todo' %}" title="{{APPNAME}}, a work in continuous evolution"><span>To Do</span></a></li>
  </ul>
</div>

web_registration/templates/password_reset.html
{% extends base_template %}

{% load staticfiles %}

{% block section %}

{% if user.is_authenticated %}

  <p>Hello <a href="{% url 'serials:user_main' user_name=user.username %}">{{user.username}}</a>, you are already logged-in, 
  so you don't need to use the e-mail password-reset functionality.</p>

{% else %}

  {% if form.errors %}
    <p class="error">The e-mail you supplied is not valid. Please try again:</p>
  {% else %}
    <p>Please, enter the e-mail to send a password-reset link:</p>
  {% endif %}
  
  <form method="post" action="{% url 'password_reset' %}">
    {% csrf_token %}
    <table>
    <tr>
      <td>{{ form.email.label_tag }}</td>
      <td>{{ form.email }}</td>
    </tr>
    <tr>
      <td><button type="submit" value="email-password-reset" name="email-password-reset" title="Send a password-reset link">
        <img alt="" src="{% static 'images/email.png' %}"/>&nbsp;Send password-reset link
      </button></td>
      <td><button type="reset" value="reset" name="reset" title="Resets e-mail address field">
        <img alt="" src="{% static 'images/eraser.png' %}"/>&nbsp;Clear
      </button></td>
    </tr>
    </table>
  </form>
  
{% endif %}

{% endblock %}

web_registration/templates/password_reset_complete.html
{% extends base_template %}

{% load staticfiles %}

{% block section %}

{% if user.is_authenticated %}

  <p>Hello <a href="{% url 'serials:user_main' user_name=user.username %}">{{user.username}}</a>, you are already logged-in, 
  so you don't need to use the e-mail password-reset functionality.</p>

{% else %}

  <h3>Password reset complete</h3>
  
  <p>Your password has been set. You may go ahead and <a href="{% url 'login' %}">log in</a> now.</p>
  
{% endif %}

{% endblock %}

web_registration/templates/password_reset_confirm.html
{% extends base_template %}

{% load staticfiles %}

{% block section %}

{% if validlink %}

  {% if form.errors %}
    <p class="error">The two password fields didn't match. Please try again:</p>
  {% else %}
    <p>Please, enter the new password you want:</p>
  {% endif %}
  
  <form method="post" action="">
    {% csrf_token %}
    <table>
    <tr>
      <td>{{ form.new_password1.label_tag }}</td>
      <td>{{ form.new_password1 }}</td>
    </tr>
    <tr>
      <td>{{ form.new_password2.label_tag }}</td>
      <td>{{ form.new_password2 }}</td>
    </tr>
    <tr>
      <td><button type="submit" value="password-reset" name="password-reset" title="Change password">
        <img alt="" src="{% static 'images/key.png' %}"/>&nbsp;Change password
      </button></td>
      <td><button type="reset" value="reset" name="reset" title="Resets passwords fileds">
        <img alt="" src="{% static 'images/eraser.png' %}"/>&nbsp;Clear
      </button></td>
    </tr>
    </table>
  </form>
  
{% else %}

  <p class="error">Sorry, but this password-reset link is no valid.</p>
  
  <p>To get a new e-mail with a new password-reset link. <a href="{% url 'password-reset' %}">click here</a>.</p>
  <p>You can also <a href="{% url 'register' %}">register as a new user...</a></p>

{% endif %}

{% endblock %}

web_registration/templates/password_reset_done.html
{% extends base_template %}

{% load staticfiles %}

{% block section %}

{% if user.is_authenticated %}

  <p>Hello <a href="{% url 'serials:user_main' user_name=user.username %}">{{user.username}}</a>, you are already logged-in, 
  so you don't need to use the e-mail password-reset functionality.</p>

{% else %}

  <h3>Password reset successful</h3>
  
  <p>We've emailed you instructions for setting your password. You should be receiving them shortly.</p>
  <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
  
{% endif %}

{% endblock %}

web_registration/templates/register.html
{% extends base_template %}

{% load staticfiles %}

{% block section %}

{% if user.is_authenticated %}
  <p>Hello <a href="{% url 'serials:user_main' user_name=user.username %}">{{user.username}}</a>, you are logged-in.</p>
{% else %}
  {% if form.errors %}
    <div class="error">
      {{form.errors}}
      <p>Please try again:</p>
    </div>
  {% else %}
    <p>Please, enter a username, an e-mail address and a password to register:</p>
  {% endif %}
  
  <form method="post" action="{% url 'register' %}">
    {% csrf_token %}
    <table>
    <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
    </tr>
    <tr>
      <td>{{ form.email.label_tag }}</td>
      <td>{{ form.email }}</td>
    </tr>
    <tr>
      <td><button type="submit" value="register" name="register" title="Register given username and password">
        <img alt="" src="{% static 'images/register.png' %}"/>&nbsp;Register!
      </button></td>
      <td><button type="reset" value="reset" name="reset" title="Resets username and e-mail address fileds">
        <img alt="" src="{% static 'images/eraser.png' %}"/>&nbsp;Clear
      </button></td>
    </tr>
    </table>
  </form>
  
  <p>You can also <a href="{% url 'login' %}">login as an existing user...</a></p>
  
{% endif %}

{% endblock %}

web_registration/templates/register_complete.html
{% extends base_template %}

{% load staticfiles %}

{% block section %}

{% if user.is_authenticated %}

  <p>Hello <a href="{% url 'serials:user_main' user_name=user.username %}">{{user.username}}</a>, you are already logged-in, 
  so you don't need to use the e-mail password-reset functionality.</p>

{% else %}

  <h3>Registration complete</h3>
  
  <p>Your password has been set. You may go ahead and <a href="{% url 'login' %}">log in</a> now.</p>
  
{% endif %}

{% endblock %}

web_registration/templates/register_confirm.html
{% extends base_template %}

{% load staticfiles %}

{% block section %}

{% if validlink %}

  {% if form.errors %}
    <p class="error">The two password fields didn't match. Please try again:</p>
  {% else %}
    <p>Please, enter the password you want:</p>
  {% endif %}
  
  <form method="post" action="">
    {% csrf_token %}
    <table>
    <tr>
      <td>{{ form.new_password1.label_tag }}</td>
      <td>{{ form.new_password1 }}</td>
    </tr>
    <tr>
      <td>{{ form.new_password2.label_tag }}</td>
      <td>{{ form.new_password2 }}</td>
    </tr>
    <tr>
      <td><button type="submit" value="register" name="register" title="Register">
        <img alt="" src="{% static 'images/key.png' %}"/>&nbsp;Register
      </button></td>
      <td><button type="reset" value="reset" name="reset" title="Resets passwords fileds">
        <img alt="" src="{% static 'images/eraser.png' %}"/>&nbsp;Clear
      </button></td>
    </tr>
    </table>
  </form>
  
{% else %}

  <p class="error">Sorry, but this register confirmation link is no valid.</p>
  
  <p>To get a new e-mail with a new register confirmation link. <a href="{% url 'password-reset' %}">click here</a>.</p>
  <p>You can also <a href="{% url 'register' %}">register as another user...</a></p>

{% endif %}

{% endblock %}

web_registration/templates/register_done.html
{% extends base_template %}

{% load staticfiles %}

{% block section %}

{% if user.is_authenticated %}

  <p>Hello <a href="{% url 'serials:user_main' user_name=user.username %}">{{user.username}}</a>, you are already logged-in, 
  so you don't need to use the e-mail password-reset functionality.</p>

{% else %}

  <h3>Registration successful</h3>
  
  <p>We've emailed you instructions for setting your password. You should be receiving them shortly.</p>
  <p>If you don't receive an email, please check your spam folder, or <a href="{% url 'password_reset' %}">ask for a new registration confirmation e-mail</a>.</p>
  
{% endif %}

{% endblock %}

web_registration/templates/register_email.html
Someone asked for registering email {{ email }} at site_name.

Follow the link below to confirm it:
{{ protocol}}://{{ domain }}{% url 'register_confirm' uidb64=uid token=token %}